[package]
name = "playground"
version = "0.1.0"
authors = ["Prajwal Tuladhar <praj@infynyxx.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
log = "0.4.8"
tempfile = "3"
assert_approx_eq = "1.1.0"