name: CI

on: [push]

jobs:
  build:
    name: hello_rust_stable
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: ["stable", "nightly"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
